name: Build and Deply

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: checkout 
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
  
    - name: Install Dependecies
    - run: npm ci

    - name: Run tests
    - run: npm test

    - name: Docker Buildx
    - uses: docker/setup-buildx-action@v3

    - name: Docker Login
    - uses: docker/login-action@v3
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docke Imagege
    - uses: docker/build-push-action@v3
      with:
        content: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/car-rental-web-app:1.0
